#!/usr/bin/env python3
"""
Google Flow Agent — AI Tool Setup
Generates AI tool configs from skills/gla:*.md (single source of truth).

Usage:
    python setup.py                  # Interactive: pick your AI tool(s)
    python setup.py --tool claude    # Generate for Claude
    python setup.py --tool gemini    # Generate for Gemini
    python setup.py --tool codex     # Generate for Codex
    python setup.py --tool all       # Generate for all tools
    python setup.py sync             # Re-sync all previously selected tools
    python setup.py clean            # Remove all generated tool configs
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent
SKILLS_DIR = ROOT / "skills"
CLAUDE_COMMANDS_DIR = ROOT / ".claude" / "commands"
GEMINI_COMMANDS_DIR = ROOT / ".gemini" / "commands" / "gla"
AGENTS_MD = ROOT / "AGENTS.md"
GEMINI_MD = ROOT / "GEMINI.md"
STATE_FILE = ROOT / ".gla-setup.json"


def discover_skills():
    """Scan skills/gla:*.md and extract name + first-line description."""
    if not SKILLS_DIR.exists():
        print(f"ERROR: skills/ directory not found at {SKILLS_DIR}")
        return []

    skills = []
    for path in sorted(SKILLS_DIR.glob("gla:*.md")):
        name = path.stem[len("gla:"):]  # strip "gla:" prefix
        description = ""
        try:
            first_line = path.read_text(encoding="utf-8").splitlines()[0].strip()
            # Strip leading markdown heading markers
            description = first_line.lstrip("#").strip()
        except (IndexError, OSError):
            description = f"{name} skill"
        skills.append({"name": name, "description": description, "path": str(path)})

    return skills


def generate_claude(skills):
    """Create .claude/commands/gla:<name>.md stubs."""
    CLAUDE_COMMANDS_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for skill in skills:
        name = skill["name"]
        dest = CLAUDE_COMMANDS_DIR / f"gla:{name}.md"
        content = (
            f"<!-- AUTO-GENERATED by setup.py — do not edit. Source: skills/ -->\n"
            f"Read and follow the instructions in skills/gla:{name}.md\n\n"
            f"Arguments: $ARGUMENTS\n"
        )
        dest.write_text(content, encoding="utf-8")
        count += 1
    print(f"Generated {count} Claude commands in .claude/commands/")
    return count


def generate_gemini(skills):
    """Create .gemini/commands/gla/<name>.toml for each skill."""
    GEMINI_COMMANDS_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for skill in skills:
        name = skill["name"]
        desc = skill["description"].replace('"', '\\"')
        dest = GEMINI_COMMANDS_DIR / f"{name}.toml"
        content = (
            f'# AUTO-GENERATED by setup.py — do not edit. Source: skills/\n'
            f'description = "{desc}"\n'
            f'prompt = "Read the skill file at skills/gla:{name}.md and follow the instructions inside. Arguments: $ARGUMENTS"\n'
        )
        dest.write_text(content, encoding="utf-8")
        count += 1
    print(f"Generated {count} Gemini commands in .gemini/commands/gla/")
    return count


def _agents_md_body(skills, title):
    """Build the shared AGENTS.md / GEMINI.md body."""
    rows = "\n".join(
        f"| `/gla:{s['name']}` | {s['description']} |" for s in skills
    )
    return (
        f"<!-- AUTO-GENERATED by setup.py — do not edit. Source: skills/ -->\n"
        f"# Google Flow Agent — {title}\n\n"
        f"## Setup\n\n"
        f"Read `CLAUDE.md` in this repo root — it contains the full API reference, rules, "
        f"workflow recipes, and pipeline order. Everything there applies to you.\n\n"
        f"## Skills\n\n"
        f"This project has reusable skills in `skills/`. When the user says `/gla:<name>`, "
        f"read `skills/gla:<name>.md` and follow the instructions inside.\n\n"
        f"Available skills:\n\n"
        f"| Skill | Purpose |\n"
        f"|-------|---------|\n"
        f"{rows}\n\n"
        f"## Pre-flight\n\n"
        f"Before any workflow, verify the server is running:\n\n"
        f"```bash\n"
        f"curl -s http://127.0.0.1:8100/health\n"
        f"# Must return: {{\"extension_connected\": true}}\n"
        f"```\n"
    )


def generate_codex(skills):
    """Generate AGENTS.md for Codex CLI."""
    content = _agents_md_body(skills, "Codex CLI Instructions")
    AGENTS_MD.write_text(content, encoding="utf-8")
    print(f"Generated AGENTS.md ({len(skills)} skills)")
    return len(skills)


def generate_gemini_md(skills):
    """Generate GEMINI.md for Gemini CLI."""
    content = _agents_md_body(skills, "Gemini CLI Instructions")
    GEMINI_MD.write_text(content, encoding="utf-8")
    print(f"Generated GEMINI.md ({len(skills)} skills)")
    return len(skills)


def save_state(tools, skill_count):
    state = {
        "tools": tools,
        "last_sync": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "skill_count": skill_count,
    }
    STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")


def load_state():
    if not STATE_FILE.exists():
        return None
    try:
        return json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def run_generators(tools, skills):
    """Run the appropriate generators for the given tool list."""
    generators = {
        "claude": generate_claude,
        "gemini": generate_gemini,
        "codex": generate_codex,
        "gemini_md": generate_gemini_md,
    }
    for tool in tools:
        if tool == "gemini":
            generators["gemini"](skills)
            generators["gemini_md"](skills)
        elif tool in generators:
            generators[tool](skills)


def do_interactive(skills):
    """Interactive mode: prompt user to pick tools."""
    print("\nGoogle Flow Agent — AI Tool Setup\n")
    print("Which AI tools do you use with this project?")
    print("  [1] Claude Code    (.claude/commands/)")
    print("  [2] Gemini CLI     (.gemini/commands/gla/ + GEMINI.md)")
    print("  [3] Codex CLI      (AGENTS.md)")
    print("  [4] All of the above")
    print()

    raw = input("Select (comma-separated, e.g. 1,2): ").strip()
    if not raw:
        print("No selection made. Exiting.")
        return

    mapping = {"1": "claude", "2": "gemini", "3": "codex", "4": "all"}
    choices = [c.strip() for c in raw.split(",")]

    tools = []
    for c in choices:
        if c not in mapping:
            print(f"Invalid choice: {c}")
            continue
        val = mapping[c]
        if val == "all":
            tools = ["claude", "gemini", "codex"]
            break
        if val not in tools:
            tools.append(val)

    if not tools:
        print("No valid tools selected. Exiting.")
        return

    run_generators(tools, skills)
    save_state(tools, len(skills))
    print(f"\nSetup complete. State saved to .gla-setup.json")


def do_tool(tool, skills):
    """Non-interactive: generate for a specific tool or all."""
    if tool == "all":
        tools = ["claude", "gemini", "codex"]
    else:
        tools = [tool]
    run_generators(tools, skills)
    save_state(tools, len(skills))
    print(f"\nSetup complete. State saved to .gla-setup.json")


def do_sync(skills):
    """Re-sync all previously selected tools."""
    state = load_state()
    if not state:
        print("No previous setup found. Run 'python setup.py' first.")
        sys.exit(1)
    tools = state.get("tools", [])
    if not tools:
        print("No tools recorded in .gla-setup.json.")
        sys.exit(1)
    print(f"Re-syncing for tools: {', '.join(tools)}")
    run_generators(tools, skills)
    save_state(tools, len(skills))
    print(f"\nSync complete. {len(skills)} skills processed.")


def do_clean():
    """Remove all generated tool configs."""
    removed = []

    # Claude commands
    if CLAUDE_COMMANDS_DIR.exists():
        for f in CLAUDE_COMMANDS_DIR.glob("gla:*.md"):
            f.unlink()
            removed.append(str(f))

    # Gemini commands dir
    if GEMINI_COMMANDS_DIR.exists():
        for f in GEMINI_COMMANDS_DIR.glob("*.toml"):
            f.unlink()
            removed.append(str(f))
        try:
            GEMINI_COMMANDS_DIR.rmdir()
        except OSError:
            pass  # not empty, leave it

    # AGENTS.md and GEMINI.md
    for md in [AGENTS_MD, GEMINI_MD]:
        if md.exists():
            first_line = md.read_text(encoding="utf-8").splitlines()[0]
            if "AUTO-GENERATED by setup.py" in first_line:
                md.unlink()
                removed.append(str(md))

    # State file
    if STATE_FILE.exists():
        STATE_FILE.unlink()
        removed.append(str(STATE_FILE))

    if removed:
        print(f"Removed {len(removed)} generated files.")
    else:
        print("Nothing to clean.")


def main():
    parser = argparse.ArgumentParser(
        description="Google Flow Agent — AI Tool Setup",
        add_help=True,
    )
    parser.add_argument(
        "subcommand",
        nargs="?",
        choices=["sync", "clean"],
        help="sync: re-sync previously selected tools | clean: remove all generated configs",
    )
    parser.add_argument(
        "--tool",
        choices=["claude", "gemini", "codex", "all"],
        help="Generate configs for a specific tool (non-interactive)",
    )

    args = parser.parse_args()

    if args.subcommand == "clean":
        do_clean()
        return

    # All other subcommands need skill discovery
    skills = discover_skills()
    if not skills and args.subcommand != "clean":
        print("No skills found in skills/gla:*.md — nothing to generate.")
        sys.exit(1)

    if args.subcommand == "sync":
        do_sync(skills)
    elif args.tool:
        do_tool(args.tool, skills)
    else:
        do_interactive(skills)


if __name__ == "__main__":
    main()
